config: fix building for iOS
otherwise failing to link because the builtin is not provided as shown
by :

  $ CC='xcrun -sdk iphoneos clang -arch arm64' make
  Undefined symbols for architecture arm64:
    "___clear_cache", referenced from:
        _sljit_generate_code in sljitLir-c23a56.o
        _sljit_set_jump_addr in sljitLir-c23a56.o
        _sljit_set_const in sljitLir-c23a56.o
  ld: symbol(s) not found for architecture arm64